document.writeln("<div class=\'assets container\'>");
document.writeln("        <div class=\'row\'>");
document.writeln("            <div class=\'col-sm-3 col-xs-6 balance\'>");
document.writeln("                <img src=\'img/bg1.png\' srcset=\'img/bg1.png 1x, img/bg1.png 2x\'");
document.writeln("                     width=\'100%\' alt=\'账户余额\'>");
document.writeln("                <p class=\'balance_nub\'>000.000</p>");
document.writeln("                <p class=\'p\'>账户余额(币)</p>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-sm-3 col-xs-6 profit\'>");
document.writeln("                <img src=\'img/bg2.png\' srcset=\'img/bg2.png 1x, img/bg2.png 2x\'");
document.writeln("                     width=\'100%\' alt=\'挖矿收益\'>");
document.writeln("                <p class=\'profit_nub\'>000.000</p>");
document.writeln("                <p class=\'p\'>挖矿收益(币)</p>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-sm-3 col-xs-6 extract\'>");
document.writeln("                <img src=\'img/bg3.png\' srcset=\'img/bg3.png 1x, img/bg3.png 2x\'");
document.writeln("                     width=\'100%\' alt=\'提成收益\'>");
document.writeln("                <p class=\'extract_nub\'>000.000</p>");
document.writeln("                <p class=\'p\'>提成收益(币)</p>");
document.writeln("            </div>");
document.writeln("            <div class=\'col-sm-3 col-xs-6 account\'>");
document.writeln("                <img src=\'img/bg4.png\' srcset=\'img/bg4.png 1x, img/bg4.png 2x\'");
document.writeln("                     width=\'100%\' alt=\'复消账户\'>");
document.writeln("                <p class=\'account_nub\'>000.0000</p>");
document.writeln("                <p class=\'p\'>复消账户(币)</p>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");