document.writeln("<div class=\'header navbar navbar-default\'>");
document.writeln("        <div class=\'container-fluid\'>");
document.writeln("            <ul class=\'header-list navbar-header\'>");
document.writeln("                <!--<div class=\'navbar-brand\'>-->");
document.writeln("                <li class=\'sy xian\'>");
document.writeln("                    <img src=\'img/logo_nce.png\' alt=\'logo\'>");
document.writeln("                    <a href=\'index.html\' class=\'a\'>首页</a>");
document.writeln("                </li>");
document.writeln("                <!--</div>-->");
document.writeln("                <button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\' data-target=\'#navbar-gbtag\' aria-expanded=\'false\'>");
document.writeln("                    <span class=\'sr-only\'>点我啊</span>");
document.writeln("                    <span class=\'icon-bar\'></span>");
document.writeln("                    <span class=\'icon-bar\'></span>");
document.writeln("                    <span class=\'icon-bar\'></span>");
document.writeln("                </button>");
document.writeln("            </ul>");
document.writeln("            <div class=\'collapse navbar-collapse\' id=\'navbar-gbtag\' >");
document.writeln("                <ul class=\'nav navbar-nav\'>");
document.writeln("                    <li class=\'dropdown\'>");
document.writeln("");
document.writeln("                        <a href=\'javascript:void(0)\' class=\'a dropdown-toggle\' data-toggle=\'dropdown\' ");
document.writeln("                           role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>");
document.writeln("                            矿机 <img src=\'img/dropdown.png\' alt=\'\'></a>");
document.writeln("                        <ul class=\'dropdown-menu\'>");
document.writeln("                            <li><a href=\'kj_dqkj.html\'>当前矿机</a></li>");
document.writeln("                            <li><a href=\'kj_kjjg.html\'>矿机架构</a></li>");
document.writeln("                            <li><a href=\'kj_glkj.html\'>关联矿机</a></li>");
document.writeln("                            <li><a href=\'kj_zckj.html\'>注册矿机</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'dropdown\'>");
document.writeln("                        <a href=\'javascript:void(0)\' class=\'a dropdown-toggle\' data-toggle=\'dropdown\'");
document.writeln("                           role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>");
document.writeln("                            资产 <img src=\'img/dropdown.png\' alt=\'\'></a>");
document.writeln("                        <ul class=\'dropdown-menu\'>");
document.writeln("                            <li><a href=\'financial_records.html\'>财务记录</a></li>");
document.writeln("                            <li><a href=\'assets_personal.html\'>个人资产</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'dropdown\'>");
document.writeln("                        <a href=\'javascript:void(0)\' class=\'a dropdown-toggle\' data-toggle=\'dropdown\'");
document.writeln("                           role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>");
document.writeln("                            安全 <img src=\'img/dropdown.png\' alt=\'\'></a>");
document.writeln("                        <ul class=\'dropdown-menu\'>");
document.writeln("                            <li><a href=\'zhaq-jbxx.html\'>基本信息</a></li>");
document.writeln("                            <li><a href=\'zhaq-scyz.html\'>双重验证</a></li>");
document.writeln("                            <li><a href=\'zhaq-sfyz.html\'>身份验证</a></li>");
document.writeln("                            <li><a href=\'zhaq-zczh.html\'>资产账号</a></li>");
document.writeln("                            <li><a href=\'zhaq-dlls.html\'>登录历史</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'dropdown\'>");
document.writeln("                        <a href=\'javascript:void(0)\' class=\'a dropdown-toggle\' data-toggle=\'dropdown\'");
document.writeln("                           role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>");
document.writeln("                            交易 <img src=\'img/dropdown.png\' alt=\'\'></a>");
document.writeln("                        <ul class=\'dropdown-menu\'>");
document.writeln("                            <li><a href=\'otc.html\'>NCE购买</a></li>");
document.writeln("                            <li><a href=\'entryOrders.html\'>用户挂单</a></li>");
document.writeln("                            <li><a href=\'offSiteDeal.html\'>我的订单</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'caactivity.html\' class=\'a\'>活动</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'\' class=\'a\'>公告</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'dzqb.html\' class=\'a\'>钱包</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'dropdown\'>");
document.writeln("                        <a href=\'javascript:void(0)\' class=\'a dropdown-toggle\' data-toggle=\'dropdown\'");
document.writeln("                           role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>");
document.writeln("                            更多 <img src=\'img/dropdown.png\' alt=\'\'></a>");
document.writeln("                        <ul class=\'dropdown-menu\'>");
document.writeln("                            <li><a href=\'slzx.html\'>算力中心</a></li>");
document.writeln("                            <li><a href=\'entryOrders.html\'>帮助中心</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'user dropdown\'>");
document.writeln("                        <a href=\'javascript:void(0)\' class=\'user_img a dropdown-toggle\' data-toggle=\'dropdown\'");
document.writeln("                           role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>");
document.writeln("                            <img src=\'img/icon_via.png\' alt=\'用户头像\'></a>");
document.writeln("                        <ul class=\'user_list dropdown-menu\'>");
document.writeln("                            <li><a href=\'\'>用户姓名</a></li>");
document.writeln("                            <li><a href=\'\'><img src=\'img/icon_exit.png\' alt=\'\'>安全退出</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("                <div class=\'clearfix\'></div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");